apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-did-cluster
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh:
      publicKeyName: maipol
 
